---
name: Linting
on:
  push:
    branches-ignore:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  linting:
    uses: ./.github/workflows/reusable-linting.yaml
    permissions:
      contents: read
      packages: read
      statuses: write
      checks: write
